name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy 
      uses: helaili/jekyll-action@v2
      with:
          token: ${{ secrets.RASTA_SECRET_TOKEN }}
          target_branch: 'gh-pages'

